#Anti-Xray Config

#Possible storage types: sqlite (default), mysql
storageType: "sqlite"

#MySQL settings
#This part of the config is only neede if storageType is set to 'mysql'
mysql:
  server: "localhost"
  port: "3306"
  database: "db"
  username: "user"
  password: "pass"